"""add users.age column

Revision ID: 3f004c500522
Revises: a48bb2d70078
Create Date: 2026-03-23 21:11:42.718022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f004c500522'
down_revision: Union[str, None] = 'a48bb2d70078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.create_index('idx_users_age', 'users', ['age'], unique=False)
    op.create_index('idx_users_gender', 'users', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_gender', table_name='users')
    op.drop_index('idx_users_age', table_name='users')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
