"""create_subscription_product_association

Revision ID: create_sub_assoc
Revises: change_age_to_date_of_birth
Create Date: 2026-04-12 22:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from core.db import GUID

# revision identifiers, used by Alembic.
revision: str = 'create_sub_assoc'
down_revision: Union[str, None] = 'change_age_to_date_of_birth'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_product_association',
    sa.Column('subscription_id', GUID(), nullable=False),
    sa.Column('product_variant_id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['catalog.product_variants.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['commerce.subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id', 'product_variant_id'),
    schema='commerce'
    )
    op.create_index('idx_sub_product_association_variant', 'subscription_product_association', ['product_variant_id'], unique=False, schema='commerce')
    op.create_index('idx_sub_product_association_subscription', 'subscription_product_association', ['subscription_id'], unique=False, schema='commerce')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sub_product_association_subscription', table_name='subscription_product_association', schema='commerce')
    op.drop_index('idx_sub_product_association_variant', table_name='subscription_product_association', schema='commerce')
    op.drop_table('subscription_product_association', schema='commerce')
    # ### end Alembic commands ###
