"""fix_product_category_schema

Revision ID: 5a2f22565cbc
Revises: 82ecb9eb384f
Create Date: 2026-03-24 10:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2f22565cbc'
down_revision: Union[str, None] = '82ecb9eb384f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop the old category_id column if it still exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('products')]
    
    if 'category_id' in columns:
        # Drop the old category_id column
        op.drop_column('products', 'category_id')
    
    # Ensure category column exists and is properly configured
    if 'category' not in columns:
        op.add_column('products', sa.Column('category', sa.String(length=100), nullable=False, server_default='Cereal Crops'))
        op.create_index('idx_products_category_status', 'products', ['category', 'product_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the old category_id column
    op.add_column('products', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
