"""Update product category from foreign key to string enum

Revision ID: 82ecb9eb384f
Revises: 3211eeac4fd6
Create Date: 2026-03-24 02:06:47.714920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82ecb9eb384f'
down_revision: Union[str, None] = '3211eeac4fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.drop_index('idx_products_category_status', table_name='products')
    op.drop_table('categories')
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=False, server_default='Cereal Crops'))
    op.create_index('idx_products_category_status', 'products', ['category', 'product_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'])
    op.drop_index('idx_products_category_status', table_name='products')
    op.create_index('idx_products_category_status', 'products', ['category_id', 'product_status'], unique=False)
    op.drop_column('products', 'category')
    op.create_table('categories',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='categories_pkey'),
    sa.UniqueConstraint('name', name='categories_name_key')
    )
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    op.create_index('ix_categories_created_by', 'categories', ['created_by'], unique=False)
    op.create_index('ix_categories_created_at', 'categories', ['created_at'], unique=False)
    op.create_index('idx_categories_name', 'categories', ['name'], unique=False)
    op.create_index('idx_categories_active', 'categories', ['is_active'], unique=False)
    # ### end Alembic commands ###
